# Generated by Django 4.2.13 on 2024-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='places')),
                ('title', models.CharField(max_length=250, null=True)),
                ('text', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
