# Generated by Django 4.2.13 on 2024-10-26 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 16, 42, 52, 425891)),
            preserve_default=False,
        ),
    ]
