# Generated by Django 4.2.13 on 2024-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='img',
        ),
        migrations.AddField(
            model_name='profession',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='professions'),
        ),
        migrations.AddField(
            model_name='profession',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='professions'),
        ),
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='places'),
        ),
    ]
