# Generated by Django 3.2.22 on 2023-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page_pk',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
